// Auth Actions
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const SEND_RESETPASSWORD_EMAIL_START ='SEND_RESETPASSWORD_EMAIL_START';
export const SEND_RESETPASSWORD_EMAIL_SUCCESS='SEND_RESETPASSWORD_EMAIL_SUCCESS';
export const  SEND_RESETPASSWORD_EMAIL_FAILURE='SEND_RESETPASSWORD_EMAIL_FAILURE';